name: Publish SDK to Maven Central

on:
  workflow_dispatch:
    branches:
      - master

permissions:
  contents: read

env:
  CI: true
  ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
  ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_PASSWORD }}
  ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK Tools
        run: |
          sdkmanager "platform-tools" \
                     "platforms;android-34" \
                     "build-tools;34.0.0" \
                     "cmdline-tools;latest" \
                     "ndk;25.2.9519653" \
                     "cmake;3.22.1"

      - name: Generate sdk.properties
        run: |
          echo "wiliotApiKey=${{ secrets.TEST_WILIOT_API_KEY }}" > sdk.properties

      - name: Publish SDK modules to Maven Central
        run: |
          ./gradlew publishToMavenCentral --stacktrace